### ISSUE TITLE
Version 3.6.1: Lost Site/Settings

### ISSUE THREAD

**Issue by m-art-in** [Daniel-KM/Omeka-S-module-UniversalViewer#10]
After the update to 3.6.1 from 3.6.0 the menu "Universal Viewer" is missing under Sites->Settings. Can this error be reproduced? This is the case with default theme 1.4.1. as well as 1.4.2. When I go back to Universal Viewer 3.6.0, the menu with the settings reappears.

**3.6.1:**
![image](https://user-images.githubusercontent.com/15324884/68758116-7970d280-060d-11ea-83b3-739576ff63ec.png)

**3.6.0**
![image](https://user-images.githubusercontent.com/15324884/68758172-93aab080-060d-11ea-9d49-3af4eb38f084.png)

**Comment by Daniel-KM** [comment]
No, it's not an error. 
In many modules, there are settings that manage the display or not of the feature in each place of the theme. But these settings are boring and generally, the theme designer choose to display them in a specific place, so remove the automatic display.
Nevertheless, in some cases, these settings are useful. So now they are managed simpler and better via a new module, [BlocksDisposition](https://github.com/Daniel-KM/Omeka-S-module-BlocksDisposition).

**Comment by m-art-in** [comment]
Thank you very much for your explanations. One more question please: If I want to see the settings, I have to install the module **BlockDsposition** or there would be another possibility e.g.  to configure a json file directly on the server to control the universalviewer's behavior?

**Comment by Daniel-KM** [comment]
The other possibility is to edit the theme directly with the view helper `echo $this->universalViewer($item);`. The old settings just did that automatically.

**Comment by Daniel-KM** [comment]
So the settings were removed from the database. If you want to know your old settings, go to your last backup.
