### ISSUE TITLE
Universal Viewer not loading images

### ISSUE THREAD

**Issue by dddana** [Daniel-KM/Omeka-S-module-UniversalViewer#11]
Hello-

We've installed IIF Server and Universal Viewer in Omeka-S and added a Universal Viewer block to a page, then attaching 4 .jpg items.

When I load the page http://celt.reclaimhosting.com/omeka-s/s/test-cd/page/ASB  there are no images displayed.  An empty div is created for Universal Viewer

The Console provides this

    Unhandled promise rejection 
    SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    Stack trace:
    [1]</</</t</t.parse@http://celt.reclaimhosting.com/omeka- s/modules/UniversalViewer/asset/vendor/uv/uv.js?v=3.6.1:4:10586
    [1]</</</t</n.prototype.load/</<@http://celt.reclaimhosting.com/omeka-s/modules/UniversalViewer/asset/vendor/uv/uv.js?v=3.6.1:3:27404
    g@http://celt.reclaimhosting.com/omeka-s/modules/UniversalViewer/asset/vendor/uv/lib/offline.js?v=3.6.1:17:10016
    F/<@http://celt.reclaimhosting.com/omeka-s/modules/UniversalViewer/asset/vendor/uv/lib/offline.js?v=3.6.1:17:10138
    k@http://celt.reclaimhosting.com/omeka-s/modules/UniversalViewer/asset/vendor/uv/lib/offline.js?v=3.6.1:17:14293
    offline.js:17:10369
    Source map error: request failed with status 404
    Resource URL: http://celt.reclaimhosting.com/omeka-s/modules/UniversalViewer/asset/vendor/uv/lib/offline.js?v=3.6.1
    Source Map URL: shim.min.js.map[Learn More]

Can you assist? 

Best,
Dana

**Comment by Daniel-KM** [comment]
There is an issue in the server so manifest cannot be created :(http://celt.reclaimhosting.com/omeka-s/iiif/12383/manifest. Can you enable logging to see issue (https://omeka.org/s/docs/user-manual/errorLogging/) ?

**Comment by dddana** [comment]
Ok thank you! 

Here's what I found in 'application.log' 

	2020-01-13T19:11:25+00:00 ERR (3): Omeka\Service\Exception\RuntimeException: Cannot manage settings when no target ID is set. in /home/keeneedu/public_html/omeka-s/application/src/Settings/AbstractTargetSettings.php:97
	Stack trace:
	#0 /home/keeneedu/public_html/omeka-s/application/src/Settings/AbstractSettings.php(149): Omeka\Settings\AbstractTargetSettings->setCache()
	#1 /home/keeneedu/public_html/omeka-s/application/src/Settings/AbstractSettings.php(95): Omeka\Settings\AbstractSettings->cache()
	#2 /home/keeneedu/public_html/omeka-s/application/src/Settings/AbstractTargetSettings.php(71): Omeka\Settings\AbstractSettings->get('metadata_browse...', Array)
	#3 /home/keeneedu/public_html/omeka-s/modules/MetadataBrowse/Module.php(180): Omeka\Settings\AbstractTargetSettings->get('metadata_browse...', Array)
	#4 /home/keeneedu/public_html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): MetadataBrowse\Module->repValueHtml(Object(Zend\EventManager\Event))
	#5 /home/keeneedu/public_html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(144): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
	#6 /home/keeneedu/public_html/omeka-s/application/src/Api/Representation/ValueRepresentation.php(55): Zend\EventManager\EventManager->trigger('rep.value.html', Object(Omeka\Api\Representation\ValueRepresentation), Object(ArrayObject))
	#7 /home/keeneedu/public_html/omeka-s/modules/IiifServer/src/View/Helper/IiifManifest.php(555): Omeka\Api\Representation\ValueRepresentation->asHtml()
	#8 [internal function]: IiifServer\View\Helper\IiifManifest->IiifServer\View\Helper\{closure}(Object(Omeka\Api\Representation\ValueRepresentation))
	#9 /home/keeneedu/public_html/omeka-s/modules/IiifServer/src/View/Helper/IiifManifest.php(556): array_map(Object(Closure), Array)
	#10 /home/keeneedu/public_html/omeka-s/modules/IiifServer/src/View/Helper/IiifManifest.php(507): IiifServer\View\Helper\IiifManifest->valuesAsHtml(Array)
	#11 /home/keeneedu/public_html/omeka-s/modules/IiifServer/src/View/Helper/IiifManifest.php(127): IiifServer\View\Helper\IiifManifest->iiifMetadata(Object(Omeka\Api\Representation\ItemRepresentation))
	#12 /home/keeneedu/public_html/omeka-s/modules/IiifServer/src/View/Helper/IiifManifest.php(70): IiifServer\View\Helper\IiifManifest->buildManifestItem(Object(Omeka\Api\Representation\ItemRepresentation))
	#13 /home/keeneedu/public_html/omeka-s/modules/IiifServer/src/Controller/PresentationController.php(154): IiifServer\View\Helper\IiifManifest->__invoke(Object(Omeka\Api\Representation\ItemRepresentation))
	#14 /home/keeneedu/public_html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): IiifServer\Controller\PresentationController->itemAction()
	#15 /home/keeneedu/public_html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
	#16 /home/keeneedu/public_html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
	#17 /home/keeneedu/public_html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
	#18 /home/keeneedu/public_html/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
	#19 /home/keeneedu/public_html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
	#20 /home/keeneedu/public_html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
	#21 /home/keeneedu/public_html/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
	#22 /home/keeneedu/public_html/omeka-s/index.php(21): Zend\Mvc\Application->run()
	#23 {main}

**Comment by dddana** [comment]
I just uninstalled Metadata Browse 1.2.0 and now things seem to work. I'll test a bit more, and then try the latest release of Metadata Browse 1.3.0 and get back to you right away.

**Comment by dddana** [comment]
I was able to get the Universal Viewer to display with Metadata Browse v 1.3.0 (uninstalled again though while we continue to explore Omeka-S.   Thank you for everything you do. Also appreciate that you directed me to the error log which helped me do a better search for solutions. 

Shall I close this or is there data you're interested in ?

**Comment by Daniel-KM** [comment]
Indeed, the last dev version of Metadata Browse has a fix that allows to use it with IiifServer.
