### ISSUE TITLE
UV wrecks havoc on site theme

### ISSUE THREAD

**Issue by brimwats** [Daniel-KM/Omeka-S-module-UniversalViewer#13]
For some reason I can't get jsviewer installed, or mirador working (clicking the Learn More link in the tiling just brings to a wiki page not about tiling, so idk how to do the query so all the mirador server things just show a blank placeholder).

But anyhow, this is related to UV. Everything works fine until I activate UV then my whole theme background goes black and it loads all wonky. Not exactly sure. You can see it in action here: https://brimwats.com/obscena/s/obsc/item/1549 (note that this omeka contains some material of an adult nature--this one is SFW however)

**Comment by GitByrd** [comment]
I'm having the same issue - it looks like UV pulls in a style sheet with rules that overwrite those in body and html tags, as well as other elements. It would be nice if the style sheet used in the module would be self-contained within a div container.

**Comment by Daniel-KM** [comment]
There is a new version of IIIF Server/UV that probably fixes this issue. The point about the config/css is separated, the module just includes the viewer automatically, it can't fix css for any theme.
