### ISSUE TITLE
Problems to disaplay UV when array_length is greater than 600

### ISSUE THREAD

**Issue by m-art-in** [Daniel-KM/Omeka-S-module-UniversalViewer#14]
In the documentation is an example how to integrate the Universalviewer into Omeka S theme. Background: I get from a parent item all other items that are set with dcterm:hasPart. This works fine and I call it like in the example:
```
    // Display multiple resources (items and/or item sets). 
    echo $this->universalViewer($resources);

```
if the array $resources is greater than 600 uv is not loaded anymore. I suspect that the URL might be too long. Apache gives a warning (File Size to long). So I suspect that a URL call like this 

`http://MYADRESS.COM/omeka-s/iiif/collection/10757,10787,10790,10793, [n+1]... [n+599] `
simply cannot work if the number of items is to great.

I suppose apache would accept a URL that would look something like this:

`http://MYADRESS.COM/omeka-s/iiif/collection/showItems?10757&10787&10790&10793&[n+1]&[n+599]`
 
instead of comma separated.
So maybe it's more an issue of [Omeka-S-module-IiifServer](https://github.com/Daniel-KM/Omeka-S-module-IiifServer/issues/20)?

**Comment by Daniel-KM** [comment]
Ok, it's interesting. I'm currently integrating iiif api v3, so I'll take care of this.

**Comment by Daniel-KM** [comment]
Note that this url is not standard in iiif, but it's useful to create random manifest (dynamic collection).

**Comment by Daniel-KM** [comment]
In fact, an url like `/iiif/set?10757&10787&…` or the more url friendly `/iiif/set?id[]=10757&id[]=10787&…` will be preferable to avoid to mix iiif and this hack.
