### ISSUE TITLE
Block is only displaying one of attached media

### ISSUE THREAD

**Issue by amoe** [Daniel-KM/Omeka-S-module-UniversalViewer#16]
Hi there, I am trying to show a selection of different .png media that can be navigated using the UV.  But when I create a block with multiple media, only 1 of the .png files, the first one attached to the block, is shown in the contents page of the UV.  Am I doing something wrong?

![2020-06-03-100106_1181x619_scrot](https://user-images.githubusercontent.com/883725/83617514-16329780-a581-11ea-945d-7e66bbc00ca4.png)
![2020-06-03-100125_682x714_scrot](https://user-images.githubusercontent.com/883725/83617516-1763c480-a581-11ea-82fa-3ea904975015.png)

**Comment by Daniel-KM** [comment]
This is fixed in version for Omeka 3.
