### ISSUE TITLE
Would be Nice to have Config Control of Where UV Appears

### ISSUE THREAD

**Issue by Bosterm** [Daniel-KM/Omeka-S-module-UniversalViewer#19]
I'm currently working on integrating the universal viewer into a custom theme I helped to develop, and it would be nice to have greater control over whether and where the viewer appears on item show/browse pages, as well as item set show/browse pages. Specifically for my needs, I would like to be able to move the viewer on the item show page to above metadata values on item show pages like media embeds typically are. However, there isn't a particularly elegant way to do this solely with theme editing, since this module quite explicitly ties itself to the 'item.show.after' trigger.

In any case, I'm going to make a fork that switches the trigger to 'item.show.before', but I hope this module adds support for configs that make it possible to move things around without having to modify the code of the module.

**Comment by Daniel-KM** [comment]
This is more a theme setting than a site setting, and this is a reason why I moved config to module Blocks Disposition. 

Ideally, this fix should not be done in this module, but in the module Blocks Disposition, that allows to choose order in the last trigger. If the module would be able to manage the "before" trigger too, it will be usable with any module. In fact, more generally, the resources pages should be manageable as the site pages, with blocks to move. It was the idea of the [Blocks Disposition](https://github.com/Daniel-KM/Omeka-S-module-BlocksDisposition). And the default content of the resource pages (default render, metadata) should be blocks too.
