### ISSUE TITLE
Don’t work when language without configuration file is used

### ISSUE THREAD

**Issue by pols12** [Daniel-KM/Omeka-S-module-UniversalViewer#2]
I tried to set French before English in configuration form. However, it makes UV do not work, failing to get /modules/UniversalViewer/asset/vendor/uv/lib/uv-mediaelement-extension.fr.config.json which do not exist.

Since English is configured as second choice, UV should not fail but should try to get the configuration for the second language, and then maybe try to get a default configuration file.

**Comment by Daniel-KM** [comment]
The language is not yet fully integrated.

**Comment by Daniel-KM** [comment]
La dernière version 3.6.0 est en français et c'est avec Univesal Viewer 3.0.
