### ISSUE TITLE
Images not displaying in original resolution

### ISSUE THREAD

**Issue by scottmetoyer** [Daniel-KM/Omeka-S-module-UniversalViewer#22]
We are using the Universal Viewer module in addition to your IIIf Server and Image Server modules.

I have "Default display of images" set to Original, and "Fallback when there is no tile" set to Tile with Original in settings, however we are seeing reduced resolution images in Universal Viewer (not the full resolution original images).

I took a look at the IIIF manifest for the item we are viewing and saw this:

```
"resource": {
      "@id": "https://omeka.ucr.edu/collections/iiif/3/2227/full/634,800/0/default.jpg",
      "@type": "dctypes:Image",
      "format": "image/jpeg",
      "width": 3640,
      "height": 4592,
      "service": {
        "@context": "3",
        "@id": "https://omeka.ucr.edu/collections/iiif/3/2227",
        "profile": "2"
}
```

The width and height parameters are correct, but the id URL seems to indicate a much smaller resolution (634x800) and browsing to the URL in the id parameter shows a blurry image similar to what we are seeing in UV.

Any idea what we're doing wrong? Thanks!

**Comment by jairomelo** [comment]
Hi @scottmetoyer, did you found how to resolve this issue? We're stuck with the same problem 😞

**Comment by jairomelo** [comment]
Check the following:

In IIIF Server module config:
* Default IIIF api version of the manifest = 2

In Image Server module config:
* Default IIIF image api version = Image Api 2

That worked for us.

**Comment by scottmetoyer** [comment]
That did the trick. Thanks!
