### ISSUE TITLE
The library "Universal Viewer" should be installed. See module’s installation documentation.

### ISSUE THREAD

**Issue by macros46** [Daniel-KM/Omeka-S-module-UniversalViewer#24]
Omeka-S version 4.0.0, 
Universal Viewer 3.6.6

seems in "Module.php", line 59:

"$js = __DIR__ . '/asset/vendor/uv/uv.js';"   -> "$js = __DIR__ . '/asset/vendor/uv3/uv.js';"

fixes the problem.

Regards

**Comment by Daniel-KM** [comment]
Thanks, it's fixed in v3.6.7.
