### ISSUE TITLE
PDF Sidebar Display Issue

### ISSUE THREAD

**Issue by yanyufish** [Daniel-KM/Omeka-S-module-UniversalViewer#4]
Hi,

After toggling the sidebar, The pdf thumbnail view doesn't fill up the whole sidebar container and the thumbnailSelectionRing shifts to the upper left a little (see the following screenshot).
![screenshot 1](https://user-images.githubusercontent.com/18058881/35360525-0052f8f2-012c-11e8-8247-cd03d5d28807.png)

Could someone fix it?

Thanks

**Comment by Daniel-KM** [comment]
This is related to the viewer itself. So could you ask on https://github.com/universalviewer/universalviewer?
