### ISSUE TITLE
Compatibility with Omeka-S 2.*

### ISSUE THREAD

**Issue by m-art-in** [Daniel-KM/Omeka-S-module-UniversalViewer#7]
Will there be an update for the Omeka-S-Branch 2.* soon? Right now there is still an error on the modules page in the backend:

`Error: Universal Viewer requires Omeka S ^1.2.0`
and also:
`Error: IIIF Server requires Omeka S ^1.2.0`

**Comment by m-art-in** [comment]
Just tested: all fine - also with other modules.
Thank you

**Comment by Daniel-KM** [comment]
Thanks, I just pushed the update.
